version: "3"

services:
  aqua_track:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./aqua_track:/aqua_track
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=aqua_track_db
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=aqua_track_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password