# Generated by Django 2.1.15 on 2022-01-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='description',
            field=models.CharField(default='My aquarium description.', max_length=255),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='height_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='is_planted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='length_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='width_cm',
            field=models.IntegerField(default=0),
        ),
    ]
